from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator


class User(AbstractUser):
    mobile = models.CharField(
        "Mobile No.",
        validators=[
            RegexValidator(
                regex="^[6-9]\d{9}$",
                message="Invalid Indian mobile number!",
                code="invalid",
            )
        ],
        max_length=10,
        null=False,
        blank=False,
    )

    emp_id = models.CharField(
        "Employee ID",
        validators=[
            RegexValidator(
                regex="^[A-Za-z]{3}\d{5}$",
                message="Invalid employee ID! Should be of form ABC12345.",
                code="invalid",
            )
        ],
        max_length=8,
        null=False,
        blank=False,
    )


class Admin(User):
    # username
    # first_name
    # last_name
    # email
    # mobile
    # org
    # emp_id
    org = models.CharField("Organization", max_length=50, null=False, blank=False)

class Manager(User):
    # username
    # first_name
    # last_name
    # email
    # mobile
    # emp_id
    # my_admin
    my_admin = models.ForeignKey(Admin, on_delete=models.CASCADE)

class HRManager(User):
    # username
    # first_name
    # last_name
    # email
    # mobile
    # emp_id
    # my_admin
    my_admin = models.ForeignKey(Admin, on_delete=models.CASCADE)

class Employee(User):
    # username and emp_id to be 
    # generated by the system

    # first_name
    # last_name
    # email
    # mobile
    # gender
    # dob
    # start_date
    # end_date
    
    gender_type = (
        ('M', "Male"),
        ("F", "Female"),
    )
    gender = models.TextChoices(gender_type)
    dob = models.DateField("Date Of Birth", null=False, blank=False)
    start_date = models.DateField('Start Date', null=False, blank=False)
    quit_date = models.DateField("Quit Date", null=True, blank=True)
