from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    mobile = models.CharField("Mobile No.", max_length=10, null=False, blank=False)
    emp_id = models.CharField("Employee ID", max_length=8, null=False, blank=False)


class Admin(User):
    # username
    # first_name
    # last_name
    # email
    # mobile
    # org
    # emp_id
    org = models.CharField("Organization", max_length=50, null=False, blank=False)


class Manager(User):
    # username
    # first_name
    # last_name
    # email
    # mobile
    # emp_id
    # my_admin
    my_admin = models.ForeignKey(Admin, on_delete=models.CASCADE)


class HRManager(User):
    # username
    # first_name
    # last_name
    # email
    # mobile
    # emp_id
    # my_admin
    my_admin = models.ForeignKey(Admin, on_delete=models.CASCADE)


class Employee(User):
    # username and emp_id to be
    # generated by the system

    # first_name
    # last_name
    # email
    # mobile
    # gender
    # dob
    # start_date
    # end_date
    # my_manager

    gender = models.CharField(max_length=1, null=False, blank=False)
    dob = models.DateField("Date Of Birth", null=False, blank=False)
    start_date = models.DateField("Start Date", null=False, blank=False)
    quit_date = models.DateField("Quit Date", null=True, blank=True)
    my_manager = models.ForeignKey(Manager, on_delete=models.CASCADE)
    my_hr = models.ForeignKey(HRManager, on_delete=models.CASCADE)