# Generated by Django 4.1.5 on 2023-02-07 08:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewEmployees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=20, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Last Name"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid",
                                message="Invalid Indian mobile number!",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                        verbose_name="Mobile No.",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("dob", models.DateField(verbose_name="Date Of Birth")),
                ("start_date", models.DateField(verbose_name="Start Date")),
                (
                    "quit_date",
                    models.DateField(blank=True, null=True, verbose_name="Quit Date"),
                ),
                (
                    "my_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.manager",
                    ),
                ),
            ],
        ),
    ]
